/*
 * Copyright 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.android.horologist.remotecompose.fontvariation.codegen

import com.google.android.horologist.remotecompose.fontvariation.DEFAULT_TOLERANCE_PIXELS
import com.google.android.horologist.remotecompose.fontvariation.VariableFont
import com.google.android.horologist.remotecompose.fontvariation.outline

/**
 * Writes Kotlin source for one fixed text: its [VariableTextOutline][outline], worked out now and
 * kept as an encoded string constant, and a `@RemoteComposable` that draws it with
 * `RemoteVariableFontText(outline, …)`. The app then needs neither the font nor any layout when it
 * makes a document: it decodes a string.
 */
internal object VariableFontCodegen {
  fun generate(
    packageName: String,
    functionName: String,
    font: VariableFont,
    fontName: String,
    text: String,
    axes: List<String>,
    location: Map<String, Float> = emptyMap(),
    pixelSize: Float? = null,
    tolerancePixels: Float = DEFAULT_TOLERANCE_PIXELS,
  ): String {
    val encoded = font.outline(text, axes, location, location, pixelSize, tolerancePixels).encode()
    val simplified = pixelSize?.let { "// Simplified for $it px, to within $tolerancePixels px." }
    val outlineName = functionName.replaceFirstChar { it.lowercase() } + "Outline"
    return buildString {
      appendLine(HEADER)
      appendLine()
      appendLine(
        "// Generated by VariableFontCodegen: \"$text\" in $fontName, animated ${axes.joinToString()}."
      )
      simplified?.let { appendLine(it) }
      appendLine("// Do not edit; regenerate with VariableFontCodegenTest.")
      appendLine()
      appendLine("package $packageName")
      appendLine()
      appendLine("import androidx.compose.remote.creation.compose.layout.RemoteComposable")
      appendLine("import androidx.compose.remote.creation.compose.modifier.RemoteModifier")
      appendLine("import androidx.compose.remote.creation.compose.state.RemoteColor")
      appendLine("import androidx.compose.remote.creation.compose.state.RemoteDp")
      appendLine("import androidx.compose.remote.creation.compose.state.RemoteFloat")
      appendLine("import androidx.compose.remote.creation.compose.state.rc")
      appendLine("import androidx.compose.runtime.Composable")
      appendLine("import androidx.compose.ui.graphics.Color")
      appendLine(
        "import com.google.android.horologist.remotecompose.fontvariation.RemoteVariableFontText"
      )
      appendLine(
        "import com.google.android.horologist.remotecompose.fontvariation.VariableTextOutline"
      )
      appendLine()
      appendLine(
        "/** \"$text\" in $fontName, worked out ahead of time: ${encoded.length} characters, no font. */"
      )
      appendLine("internal val $outlineName: VariableTextOutline by lazy {")
      appendLine("  VariableTextOutline.decode(")
      // As ktfmt writes it: a trailing comma only when there are several arguments.
      val chunks = encoded.chunked(CHUNK)
      chunks.forEach { appendLine("    \"${escape(it)}\"" + if (chunks.size > 1) "," else "") }
      appendLine("  )")
      appendLine("}")
      appendLine()
      appendLine("/** Draws \"$text\" in $fontName with ${axes.joinToString()} animated. */")
      appendLine("@Composable")
      appendLine("@RemoteComposable")
      appendLine("internal fun $functionName(")
      axes.forEach { appendLine("  ${it.lowercase()}: RemoteFloat,") }
      appendLine("  fontSize: RemoteDp,")
      appendLine("  modifier: RemoteModifier = RemoteModifier,")
      appendLine("  color: RemoteColor = Color.Black.rc,")
      appendLine(") {")
      val arguments =
        listOf(
          outlineName,
          "mapOf(${axes.joinToString { "\"$it\" to ${it.lowercase()}" }})",
          "fontSize",
          "modifier",
          "color",
        )
      val oneLine = "  RemoteVariableFontText(${arguments.joinToString()})"
      if (oneLine.length <= 100) appendLine(oneLine)
      else {
        appendLine("  RemoteVariableFontText(")
        arguments.forEach { appendLine("    $it,") }
        appendLine("  )")
      }
      appendLine("}")
    }
  }

  /** Characters per string constant: a class file holds at most 65,535 bytes of UTF-8 in one. */
  private const val CHUNK = 16_000

  private fun escape(s: String): String = buildString {
    for (ch in s) {
      if (ch.code in 0x20..0x7e && ch != '"' && ch != '\\' && ch != '$') append(ch)
      else append("\\u%04x".format(ch.code))
    }
  }

  private val HEADER =
    """
    /*
     * Copyright 2026 The Android Open Source Project
     *
     * Licensed under the Apache License, Version 2.0 (the "License");
     * you may not use this file except in compliance with the License.
     * You may obtain a copy of the License at
     *
     *      https://www.apache.org/licenses/LICENSE-2.0
     *
     * Unless required by applicable law or agreed to in writing, software
     * distributed under the License is distributed on an "AS IS" BASIS,
     * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     * See the License for the specific language governing permissions and
     * limitations under the License.
     */
    """
      .trimIndent()
}
